# Generated by Django 3.1.2 on 2020-11-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguilearn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='learning',
        ),
        migrations.RemoveField(
            model_name='word',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='word',
            name='mastered',
        ),
    ]
