# Generated by Django 3.1 on 2020-10-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguilearn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('definition', models.CharField(max_length=1028)),
                ('example', models.CharField(max_length=1028)),
                ('phrase', models.CharField(max_length=1028)),
                ('word_of_the_day', models.BooleanField(default=False)),
                ('word_of_the_day_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_words',
            field=models.ManyToManyField(related_name='users_favourite', to='linguilearn.Word'),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_words',
            field=models.ManyToManyField(related_name='users_learning', to='linguilearn.Word'),
        ),
        migrations.AddField(
            model_name='user',
            name='mastered_words',
            field=models.ManyToManyField(related_name='users_mastered', to='linguilearn.Word'),
        ),
    ]
