# Generated by Django 3.1.2 on 2020-11-24 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguilearn', '0002_auto_20201124_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entryList',
            field=models.CharField(choices=[('1', 'Learning'), (2, 'Mastered'), ('3', 'Archived'), (4, None)], default='4', max_length=32),
        ),
        migrations.AddField(
            model_name='entry',
            name='favourites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='starred_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
