# Generated by Django 3.1 on 2020-10-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguilearn', '0002_auto_20201013_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
