# Generated by Django 3.1.2 on 2020-11-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguilearn', '0003_auto_20201124_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='stars',
            new_name='starred_by',
        ),
        migrations.AlterField(
            model_name='entry',
            name='entryList',
            field=models.CharField(choices=[('1', 'Learning'), ('2', 'Mastered'), ('3', 'Archived'), ('0', None)], default='0', max_length=32),
        ),
    ]
