# Generated by Django 3.1.2 on 2020-10-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguilearn', '0003_remove_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='example',
        ),
        migrations.RemoveField(
            model_name='word',
            name='phrase',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_of_the_day',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_of_the_day_date',
        ),
    ]
