# Generated by Django 3.1.2 on 2020-10-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguilearn', '0004_auto_20201025_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Entry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_words',
        ),
        migrations.RemoveField(
            model_name='user',
            name='learning_words',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mastered_words',
        ),
        migrations.AddField(
            model_name='user',
            name='entries_learning',
            field=models.ManyToManyField(related_name='users_learning', to='linguilearn.Entry'),
        ),
        migrations.AddField(
            model_name='user',
            name='entries_mastered',
            field=models.ManyToManyField(related_name='users_mastered', to='linguilearn.Entry'),
        ),
        migrations.AddField(
            model_name='user',
            name='entries_starred',
            field=models.ManyToManyField(related_name='users_starred', to='linguilearn.Entry'),
        ),
    ]
