# Generated by Django 3.1.2 on 2020-11-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguilearn', '0004_auto_20201124_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entryList',
            new_name='entry_list',
        ),
    ]
