# Generated by Django 3.1.2 on 2020-12-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguilearn', '0005_auto_20201124_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='customWord',
            field=models.BooleanField(default=False),
        ),
    ]
