# Generated by Django 3.1.2 on 2020-12-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguilearn', '0006_word_customword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='starred_by',
        ),
    ]
