# Generated by Django 3.1.2 on 2020-10-29 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguilearn', '0006_auto_20201026_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.CharField(max_length=255)),
                ('learning', models.ManyToManyField(related_name='users_learning', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(related_name='users_liked', to=settings.AUTH_USER_MODEL)),
                ('mastered', models.ManyToManyField(related_name='users_mastered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
